### ISSUE TITLE
Admin tools for articles

### ISSUE THREAD

**Issue by perry-** [kidsakoder/kidsakoder-no-app#10]
# User story
As an admin, I want to easily add new articles, so that I can inform site visitors of relevant news

# Additional information
- Articles may include a top image, time stamp, rich text, videos, inline images, comment section (see separate issue) and SoMe share buttons (see separate issue)
- Administrators should be able to post articles for a specific code club or for Lær Kidsa Koding globally
- Admin user rights should limit news post to their respective code club (super users should be able to post anywhere)

**Comment by siddise** [comment]
This has been done in Pull request #73 based on the new design sketches, excluding the comment section and the social media integration from other issues.
