### ISSUE TITLE
Investigate React setup

### ISSUE THREAD

**Issue by perry-** [kidsakoder/kidsakoder-no-app#3]
Might need it for forms and stuff...

**Comment by niklasmh** [comment]
It is possible to use the create-react-app tool from NPM to setup the development environment with hot-reloading and etc.. React-router may be used inside forms and small applications but is not necessary for changing URL according to pages as some pages uses static rendering / prerendering. It is also possible to use several entrypoints to acheive a server-client-render hybrid.

**Comment by perry-** [comment]
I suggest using React components at Enonic pages with regular Enonic components.  If a form is paged or if you're making a paged tutorial, react-router might be neccessary. For (mostly) everything else, the Enonic router is probably sufficient (i.e. redirects to other pages).

**Comment by siddise** [comment]
Will reconsider later in the project
